### ISSUE TITLE
QSO are not shown after import.

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#578]
Ligview refresh  is missing after a log import

**Comment by ag5ur** [comment]
In my case, they didn't appear due to `band_rx` being null or empty (both conditions existed). Comparing other contacts, I assume `bandid` and `band_rx` are just RX/TX versions of the same field, and I've never made contacts with them on separate bands, so I was able to just copy the value from `bandid` with `UPDATE log SET band_rx = bandid WHERE band_rx IS NULL OR band_rx = '';`.

#451 is potentially related, as records from `wsjtx` aren't appearing either.

**Comment by ea4k** [comment]
Closed by PR: https://github.com/ea4k/klog/pull/579
